/**
 * `haido viz` — the human window (SPEC US6): one self-contained dark HTML page,
 * zero dependencies, works from file://.
 *
 * v0.2.2 — THE BRIDGE (đài chỉ huy): a ship's-bridge console of instruments
 * around the chart. Frames: the 2D chart (hero, interactive), a 3D globe that
 * slowly rotates (same simulation, second projection), an activity band (live
 * events: who edits what), an inspector (structure + meaning of the selected
 * node) and the ship's log (memories on a timeline — the product's namesake).
 * Instrument labels sit engraved on the frame borders; readings use monospace.
 *
 * Memory is a FIRST-CLASS citizen on the map (m_boot_012): each note is a
 * diamond satellite tethered to every file/symbol it anchors to. Fresh notes
 * are ink diamonds, needs-review notes glow status-warning (never color-alone:
 * icon + label travel with the color). Anti-hairball (m_boot_011): edges stay
 * ambient; hover/click spotlights only the incident links.
 *
 * Live mode (`haido viz --live`): LIVE is baked true and the client subscribes
 * to `GET /events` (SSE). applyData() reconciles in place — surviving nodes
 * keep their positions, new ones bloom, deleted ones fade, agent edits glow
 * cyan, human edits white, and drifting notes flash yellow (m_boot_014).
 */
export function buildVizHtml(
  dataJson: string,
  repoName: string,
  lang: Lang = 'en',
  live = false,
): string {
  const safeJson = dataJson.replaceAll('<', '\\u003c');
  let page = TEMPLATE;
  if (lang === 'en') {
    // Vietnamese is the template's source language; EN is derived here so the
    // template stays single-sourced. Ordered longest-first so phrases win.
    for (const [vi, en] of EN_PAIRS) page = page.replaceAll(vi, en);
  }
  return page
    .replaceAll('__REPO_NAME__', escapeHtml(repoName)) // appears in <title> AND <h1>
    .replace('__HAIDO_LIVE__', live ? '1' : '0')
    .replace('"__HAIDO_DATA__"', safeJson);
}

type Lang = 'en' | 'vi';

const EN_PAIRS: ReadonlyArray<readonly [string, string]> = [
  [
    '⬥ = ghi chú trí nhớ neo vào file</b> (vàng ⚠ = cần review) · trỏ/click node hoặc ⬥ để soi liên kết · kéo node/nền · lăn chuột zoom — sinh bởi',
    '⬥ = a memory note anchored to a file</b> (yellow ⚠ = needs review) · hover/click a node or ⬥ to spotlight its links · drag nodes/background · wheel to zoom — generated by',
  ],
  [
    'Chưa chọn gì — click một node hoặc ⬥ trên hải đồ',
    'Nothing selected — click a node or ⬥ on the chart',
  ],
  ['(chỉ có ở chế độ --live — chạy haido viz --live)', '(live mode only — run haido viz --live)'],
  ['(file tài liệu — neo ghi chú ở mức file)', '(knowledge file — notes anchor at file level)'],
  ['đang theo dõi thay đổi', 'watching for changes'],
  ['Ghi chú neo ở đây (click để soi)', 'Notes anchored here (click to inspect)'],
  ['Chưa có ghi chú nào ở file này', 'No notes on this file yet'],
  ['ghi chú (⬥ neo vào file)', 'note (⬥ anchored to a file)'],
  ['⚠ ghi chú cần review', '⚠ note needs review'],
  ['chỉ file có ghi chú', 'only files with notes'],
  ['hiện rõ mọi liên kết', 'show all links'],
  ['hay đổi cùng nhau', 'changes together'],
  ['lọc theo đường dẫn…', 'filter by path…'],
  [' cần review (code đã đổi)', ' needs review (code changed)'],
  ['Nhật ký hải trình', "Ship's log"],
  [" cần review)'", " need review)'"],
  ['○ mất kết nối', '○ disconnected'],
  ['agent vừa sửa', 'agent just edited'],
  ['tự kết nối lại…', 'reconnecting…'],
  ['Đang diễn ra', 'Happening now'],
  ['Soi chi tiết', 'Inspector'],
  ['ghi chú mới: ', 'new note: '],
  ['⚠ cần review', '⚠ needs review'],
  ['● trực tiếp', '● live'],
  ['Ghi chú — ', 'Note — '],
  ['Địa cầu 3D', '3D globe'],
  ['toàn hải đồ', 'chart only'],
  ['Hải đồ 2D', '2D chart'],
  ['Cấu trúc', 'Structure'],
  ['Liên kết', 'Links'],
  ['đã lành', 'healed'],
  ['⬥ ghi chú', '⬥ notes'],
  [' ghi chú', ' notes'],
  [' file · ', ' files · '],
  [' symbol · ', ' symbols · '],
  [' liên kết', ' links'],
  ['>neo: ', '>anchors: '],
  ['Neo vào', 'Anchored to'],
  ['← được import bởi', '← imported by'],
  ['>vì: ', '>why: '],
  ['tạo: ', 'created: '],
  ["'(gốc)'", "'(root)'"],
  ['"đóng"', '"close"'],
  ["</span>khác'", "</span>other'"],
] as const;

function escapeHtml(s: string): string {
  return s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

const TEMPLATE = `<!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hải Đồ — __REPO_NAME__</title>
<style>
  :root {
    --page: #0d0d0d; --surface: #1a1a19;
    --ink: #ffffff; --ink-2: #c3c2b7; --ink-3: #898781;
    --hair: #2c2c2a; --border: rgba(255,255,255,0.10);
    --warn: #fab219; --agent: #57c7ff;
    --mono: ui-monospace, Consolas, 'Cascadia Mono', Menlo, monospace;
  }
  * { box-sizing: border-box; margin: 0; }
  html, body { height: 100%; }
  body {
    background: var(--page); color: var(--ink-2);
    font: 13px/1.45 system-ui, -apple-system, "Segoe UI", sans-serif;
    display: flex; flex-direction: column; overflow: hidden;
  }
  header {
    padding: 10px 14px 8px; border-bottom: 1px solid var(--hair);
    display: flex; flex-wrap: wrap; gap: 6px 16px; align-items: center; background: var(--surface);
  }
  header h1 { font-size: 14px; color: var(--ink); font-weight: 600; margin-right: 4px; }
  header .stats { color: var(--ink-3); font-family: var(--mono); font-size: 12px; }
  #live { display: none; align-items: center; font-weight: 600; }
  #live.on { color: #35b06f; }
  #live.off { color: #e5484d; }
  header label { display: inline-flex; align-items: center; gap: 5px; cursor: pointer; user-select: none; }
  header input[type="search"] {
    background: var(--page); border: 1px solid var(--hair); color: var(--ink);
    border-radius: 6px; padding: 4px 8px; width: 170px; outline: none;
  }
  header input[type="search"]:focus { border-color: var(--ink-3); }
  #legend { display: flex; flex-wrap: wrap; gap: 4px 12px; align-items: center; }
  #legend .chip { display: inline-flex; align-items: center; gap: 5px; color: var(--ink-2); }
  #legend .dot { width: 9px; height: 9px; border-radius: 50%; display: inline-block; }
  #legend .dia { width: 8px; height: 8px; display: inline-block; transform: rotate(45deg);
    background: var(--ink-2); border-radius: 1px; }
  #legend .dia.warn { background: var(--warn); }

  main.bridge {
    flex: 1; min-height: 0; padding: 14px 10px 10px; gap: 12px;
    display: grid;
    grid-template-columns: minmax(0, 1.5fr) minmax(0, 1fr);
    grid-template-rows: minmax(0, 1.35fr) minmax(0, 1fr);
    grid-template-areas: "globe chart" "deck deck";
  }
  body.maponly main.bridge {
    grid-template-columns: minmax(0,1fr); grid-template-rows: minmax(0,1fr);
    grid-template-areas: "chart"; gap: 0;
  }
  body.maponly #deck, body.maponly #globeFrame { display: none; }
  .frame {
    position: relative; border: 1px solid var(--hair); background: var(--surface);
    min-height: 0; min-width: 0; display: flex; flex-direction: column;
  }
  .frame > .plate {
    position: absolute; top: -8px; left: 12px; z-index: 2;
    background: var(--surface); padding: 0 7px;
    font-size: 10px; font-weight: 600; letter-spacing: .1em; text-transform: uppercase;
    color: var(--ink-3); border-left: 1px solid var(--hair); border-right: 1px solid var(--hair);
  }
  #globeFrame { grid-area: globe; }
  #chartFrame { grid-area: chart; }
  #deck { grid-area: deck; display: flex; gap: 12px; min-height: 0; }
  #feedFrame { flex: 1; }
  #inspectFrame { flex: 1.3; }
  #logFrame { flex: 1; }
  .stage { position: relative; flex: 1; min-height: 0; }
  .stage canvas { position: absolute; inset: 0; cursor: grab; }
  .stage canvas.dragging { cursor: grabbing; }
  .frame .body { flex: 1; min-height: 0; overflow-y: auto; padding: 12px; }
  .frame .body::-webkit-scrollbar { width: 8px; }
  .frame .body::-webkit-scrollbar-thumb { background: var(--hair); border-radius: 4px; }

  #tip {
    position: absolute; pointer-events: none; display: none; max-width: 360px; z-index: 3;
    background: var(--page); border: 1px solid var(--border); border-radius: 8px;
    padding: 7px 10px; color: var(--ink-2); box-shadow: 0 4px 18px rgba(0,0,0,.5);
  }
  #tip b { color: var(--ink); font-weight: 600; }

  #inspector h2 { font-size: 13px; color: var(--ink); word-break: break-all; }
  #inspector .meta { color: var(--ink-3); margin: 4px 0 10px; }
  #inspector .empty { color: var(--ink-3); padding: 8px 0; }
  .mem {
    border: 1px solid var(--hair); border-radius: 8px; padding: 8px 10px; margin-bottom: 8px;
    cursor: pointer;
  }
  .mem:hover { border-color: var(--ink-3); }
  .mem .t { color: var(--ink); font-weight: 600; }
  .mem .body2 { margin-top: 4px; }
  .mem .why { color: var(--ink-3); margin-top: 4px; }
  .flag { color: var(--warn); font-weight: 600; }
  .sec { color: var(--ink-3); text-transform: uppercase; font-size: 10px;
    letter-spacing: .08em; margin: 12px 0 6px; }
  .edge { padding: 2px 0; word-break: break-all; cursor: pointer; }
  .edge:hover { color: var(--ink); }
  .sym { font-family: var(--mono); font-size: 11.5px; padding: 2px 0; white-space: nowrap;
    overflow: hidden; text-overflow: ellipsis; }
  .sym .k { color: var(--ink-3); display: inline-block; width: 14px; }
  .sym .ln { color: var(--ink-3); float: right; margin-left: 8px; }
  .close { float: right; cursor: pointer; color: var(--ink-3); border: none;
    background: none; font-size: 15px; }

  #feed, #log { list-style: none; }
  #feed li, #log li {
    font-family: var(--mono); font-size: 11.5px; padding: 2.5px 0; cursor: pointer;
    white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
  }
  #feed li:hover, #log li:hover { color: var(--ink); }
  #feed .t, #log .d { color: var(--ink-3); margin-right: 7px; }
  #feed .agent { color: var(--agent); }
  #feed .warn, #log .warn { color: var(--warn); }
  #feed .ok { color: #35b06f; }
  #feedEmpty { color: var(--ink-3); }

  footer { padding: 6px 14px; border-top: 1px solid var(--hair); color: var(--ink-3);
    background: var(--surface); }
  kbd { color: var(--ink-2); }

  @media (max-width: 1120px) {
    body { overflow: auto; }
    main.bridge { display: flex; flex-direction: column; }
    #globeFrame { height: 46vh; flex: none; }
    #chartFrame { height: 46vh; flex: none; }
    #deck { flex: none; flex-direction: column; }
    #feedFrame, #inspectFrame, #logFrame { height: 250px; }
  }
</style>
</head>
<body>
<header>
  <h1>🧭 Hải Đồ — __REPO_NAME__</h1>
  <span class="stats" id="stats"></span>
  <span id="live"></span>
  <label><input type="checkbox" id="showMems" checked> ⬥ ghi chú</label>
  <label><input type="checkbox" id="showImports" checked> import</label>
  <label><input type="checkbox" id="showCochange" checked> hay đổi cùng nhau</label>
  <label><input type="checkbox" id="allEdges"> hiện rõ mọi liên kết</label>
  <label><input type="checkbox" id="onlyMem"> chỉ file có ghi chú</label>
  <label><input type="checkbox" id="mapOnly"> toàn hải đồ</label>
  <input type="search" id="search" placeholder="lọc theo đường dẫn…">
  <span id="legend"></span>
</header>
<main class="bridge">
  <section class="frame" id="globeFrame">
    <span class="plate">Địa cầu 3D</span>
    <div class="stage" id="globeStage"><canvas id="globe"></canvas></div>
  </section>
  <section class="frame" id="chartFrame">
    <span class="plate">Hải đồ 2D</span>
    <div class="stage" id="chartStage"><canvas id="canvas"></canvas><div id="tip"></div></div>
  </section>
  <div id="deck">
    <section class="frame" id="feedFrame">
      <span class="plate">Đang diễn ra</span>
      <div class="body"><ul id="feed"></ul><div id="feedEmpty">(chỉ có ở chế độ --live — chạy haido viz --live)</div></div>
    </section>
    <section class="frame" id="inspectFrame">
      <span class="plate">Soi chi tiết</span>
      <div class="body" id="inspector"></div>
    </section>
    <section class="frame" id="logFrame">
      <span class="plate">Nhật ký hải trình</span>
      <div class="body"><ul id="log"></ul></div>
    </section>
  </div>
</main>
<footer id="hint"></footer>
<script type="application/json" id="haido-data">"__HAIDO_DATA__"</script>
<script>
(function () {
  'use strict';
  var DATA = JSON.parse(document.getElementById('haido-data').textContent);
  var LIVE = ('__HAIDO_LIVE__' === '1');
  var PALETTE = ['#3987e5', '#199e70', '#c98500', '#008300', '#9085e9', '#e66767', '#d55181', '#d95926'];
  var OTHER = '#52514e';
  var TYPE_ICON = { invariant: '⛔', gotcha: '🪤', decision: '📌', convention: '📐', todo: '📝' };
  var KIND_ICON = { function: 'ƒ', method: 'ƒ', class: '◆', const: '≡', type: 'τ' };
  var NO_MOTION = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // ---- model state — reconciled in place by applyData() (live mode re-feeds it) ----
  function topDir(p) { var i = p.indexOf('/'); return i === -1 ? '(gốc)' : p.slice(0, i) + '/'; }
  var nodes = [], mems = [], edges = [];
  var byId = {}, memById = {};
  var dirs = [], dirColor = {}, perDir = {}, paletteUsed = 0, nextIdx = 0;
  var HEAT_MS = 8000, ENTER_MS = 450, EXIT_MS = 650, RIPPLE_MS = 900;
  var frameNow = 0;

  function radiusOf(symbols) { return Math.min(18, 4 + Math.sqrt(symbols || 0) * 1.6); }
  function ensureDir(d) {
    if (dirColor[d]) return;
    dirs.push(d);
    dirColor[d] = paletteUsed < PALETTE.length ? PALETTE[paletteUsed++] : OTHER;
  }
  // directory seed centers on a sphere (golden spiral) — only used to place NEW nodes
  function dirSeed(d) {
    var i = dirs.indexOf(d), N = Math.max(1, dirs.length);
    var gy = N === 1 ? 0 : 1 - 2 * (i + 0.5) / N;
    var gr = Math.sqrt(Math.max(0, 1 - gy * gy));
    var phi = i * 2.399963;
    return [Math.cos(phi) * gr * 300, gy * 240, Math.sin(phi) * gr * 300];
  }
  function seedNode(n, first, k) {
    var cx, cy, cz, i, count = 0;
    if (!first) {
      cx = 0; cy = 0; cz = 0;
      for (i = 0; i < nodes.length; i++) {
        var s = nodes[i];
        if (s.dir === n.dir && !s.dying && s !== n) { cx += s.x; cy += s.y; cz += s.z; count++; }
      }
      if (count > 0) { cx /= count; cy /= count; cz /= count; }
    }
    if (count === 0) { var c = dirSeed(n.dir); cx = c[0]; cy = c[1]; cz = c[2]; }
    var a2 = k * 2.399963;
    var rr = 24 + Math.sqrt(k) * 15;
    n.x = cx + Math.cos(a2) * rr;
    n.y = cy + Math.sin(a2) * rr;
    n.z = cz + Math.sin(a2 * 0.7) * rr * 0.6;
  }

  /**
   * One truth in, one map out: create what is new (bloom + glow), update what
   * changed, mark what disappeared as dying (fade-out), rebind memory↔file,
   * rebuild edges. Positions of surviving nodes are never touched — the map
   * must not jump under the reader's eyes.
   */
  function applyData(data, hot) {
    var now = performance.now();
    var first = nodes.length === 0 && mems.length === 0;
    var i, j;
    var events = [];

    var counts = {};
    (data.files || []).forEach(function (f) { var d = topDir(f.path); counts[d] = (counts[d] || 0) + 1; });
    // first build: biggest directories claim the palette first (stable afterwards)
    Object.keys(counts).sort(function (a, b) { return counts[b] - counts[a]; }).forEach(ensureDir);

    var seen = {};
    (data.files || []).forEach(function (f) {
      seen[f.path] = true;
      var syms = f.syms || [];
      var n = byId[f.path];
      if (n) {
        n.symbols = f.symbols || 0;
        n.syms = syms;
        n.lang = f.lang;
        n.r = radiusOf(n.symbols);
        n.dying = 0;
        return;
      }
      var dir = topDir(f.path);
      n = {
        kind: 'file', id: f.path, dir: dir, lang: f.lang, symbols: f.symbols || 0, syms: syms,
        mems: [], stale: false,
        color: dirColor[dir],
        r: radiusOf(f.symbols || 0),
        x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0, idx: nextIdx++, pinned: false,
        nbr: {}, deg: 0,
        born: first ? -1e9 : now, hotAt: first ? -1e9 : now, hotSrc: '', dying: 0,
        sx: 0, sy: 0, sr: 0, sOn: false,
        gx: 0, gy: 0, gr: 0, gdepth: 1, gOn: false
      };
      perDir[dir] = (perDir[dir] || 0) + 1;
      seedNode(n, first, perDir[dir]);
      byId[n.id] = n;
      nodes.push(n);
      if (!first) events.push(['＋', '', n.id, n.id]);
    });
    for (i = 0; i < nodes.length; i++) {
      if (!seen[nodes[i].id] && !nodes[i].dying) {
        nodes[i].dying = now;
        events.push(['−', '', nodes[i].id, null]);
      }
    }

    var seenM = {};
    (data.memories || []).forEach(function (m) {
      seenM[m.id] = true;
      var node = memById[m.id];
      if (node) {
        if (node.status !== m.status) {
          node.hotAt = now; // fresh↔needs_review flips flash
          events.push(m.status === 'needs_review'
            ? ['⚠', 'warn', (m.title || '') + ' · ⚠ cần review', m.id]
            : ['✅', 'ok', (m.title || '') + ' · đã lành', m.id]);
        }
        node.type = m.type; node.status = m.status;
        node.title = m.title || ''; node.body = m.body || ''; node.why = m.why || '';
        node.created = m.created || 0;
        node.anchors = m.anchors || [];
        node.dying = 0;
        return;
      }
      node = {
        kind: 'mem', id: m.id, type: m.type, status: m.status,
        title: m.title || '', body: m.body || '', why: m.why || '',
        created: m.created || 0,
        anchors: (m.anchors || []), files: [],
        r: 5, seeded: false,
        x: 0, y: 0, z: 0, vx: 0, vy: 0, vz: 0,
        born: first ? -1e9 : now, hotAt: first ? -1e9 : now, dying: 0,
        sx: 0, sy: 0, sr: 0, sOn: false,
        gx: 0, gy: 0, gr: 0, gdepth: 1, gOn: false
      };
      memById[node.id] = node;
      mems.push(node);
      if (!first) events.push(['⬥', '', 'ghi chú mới: ' + node.title, node.id]);
    });
    for (i = 0; i < mems.length; i++) {
      if (!seenM[mems[i].id] && !mems[i].dying) mems[i].dying = now;
    }

    // rebind memory↔file from scratch — cheap and immune to bookkeeping drift
    for (i = 0; i < nodes.length; i++) { nodes[i].mems = []; nodes[i].stale = false; }
    for (i = 0; i < mems.length; i++) {
      var mm = mems[i];
      mm.files = [];
      if (mm.dying) continue;
      var seenF = {};
      for (j = 0; j < mm.anchors.length; j++) {
        var a = mm.anchors[j];
        if (seenF[a.path]) continue;
        seenF[a.path] = true;
        var fn = byId[a.path];
        if (fn && !fn.dying) {
          mm.files.push(fn);
          fn.mems.push(mm);
          if (mm.status === 'needs_review') fn.stale = true;
        }
      }
      if (!mm.seeded) {
        mm.seeded = true;
        var base = mm.files[0] || { x: 0, y: 0, z: 0 };
        var am = i * 2.399963 + 1;
        mm.x = base.x + Math.cos(am) * 40;
        mm.y = base.y + Math.sin(am) * 40;
        mm.z = base.z + 20;
      }
    }

    edges = (data.edges || [])
      .filter(function (e) {
        var A = byId[e.src], B = byId[e.dst];
        return A && B && !A.dying && !B.dying;
      })
      .map(function (e) { return { a: byId[e.src], b: byId[e.dst], kind: e.kind, w: e.weight || 1 }; });
    for (i = 0; i < nodes.length; i++) { nodes[i].nbr = {}; nodes[i].deg = 0; }
    edges.forEach(function (e) {
      e.a.nbr[e.b.idx] = true; e.b.nbr[e.a.idx] = true;
      e.a.deg++; e.b.deg++;
    });

    // server-sent heat: a comment-only save changes no structure but still glows
    if (hot) {
      (hot.files || []).forEach(function (p) {
        if (byId[p]) { byId[p].hotAt = now; byId[p].hotSrc = ''; }
      });
      (hot.agent || []).forEach(function (p) { if (byId[p]) byId[p].hotSrc = 'agent'; });
      (hot.mems || []).forEach(function (id) { if (memById[id]) memById[id].hotAt = now; });
      (hot.files || []).forEach(function (p) {
        var n2 = byId[p];
        if (n2 && !n2.dying && n2.born < now - 1) {
          events.push(n2.hotSrc === 'agent' ? ['⚡', 'agent', p, p] : ['✎', '', p, p]);
        }
      });
    }

    if (!first) { for (i = 0; i < events.length; i++) feedEvent(events[i]); }
    refreshStats();
    renderLegend();
    renderLog();
    if (selected) {
      if (selected.dying) select(null);
      else select(selected); // panel re-renders with fresh content
    }
    alpha = Math.max(alpha, first ? 1 : 0.3);
  }

  // dying entities linger EXIT_MS for their fade-out, then leave the model
  function pruneDead(now) {
    var i, changed = false;
    var keepN = [];
    for (i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.dying && now - n.dying > EXIT_MS) { delete byId[n.id]; changed = true; }
      else keepN.push(n);
    }
    if (changed) nodes = keepN;
    var keepM = [];
    var changedM = false;
    for (i = 0; i < mems.length; i++) {
      var m = mems[i];
      if (m.dying && now - m.dying > EXIT_MS) { delete memById[m.id]; changedM = true; }
      else keepM.push(m);
    }
    if (changedM) mems = keepM;
    if (changed || changedM) {
      refreshStats();
      renderLog();
      if (selected && ((selected.kind === 'file' && !byId[selected.id]) ||
        (selected.kind === 'mem' && !memById[selected.id]))) select(null);
      if (hover && ((hover.kind === 'file' && !byId[hover.id]) ||
        (hover.kind === 'mem' && !memById[hover.id]))) hover = null;
    }
  }

  // ---- header ----
  function refreshStats() {
    var i, files = 0, sym = 0, notes = 0, staleTotal = 0;
    for (i = 0; i < nodes.length; i++) {
      if (nodes[i].dying) continue;
      files++; sym += nodes[i].symbols;
    }
    for (i = 0; i < mems.length; i++) {
      if (mems[i].dying) continue;
      notes++;
      if (mems[i].status === 'needs_review') staleTotal++;
    }
    document.getElementById('stats').textContent =
      files + ' file · ' + sym + ' symbol · ' + notes + ' ghi chú' +
      (staleTotal ? ' (⚠ ' + staleTotal + ' cần review)' : '');
  }
  function renderLegend() {
    var legend = document.getElementById('legend');
    legend.innerHTML = '';
    var shown = 0, i;
    for (i = 0; i < dirs.length && shown < PALETTE.length; i++) {
      var d = dirs[i];
      if (dirColor[d] === OTHER) continue;
      var s = document.createElement('span');
      s.className = 'chip';
      s.innerHTML = '<span class="dot" style="background:' + dirColor[d] + '"></span>' + d;
      legend.appendChild(s);
      shown++;
    }
    if (dirs.length > shown) {
      var o = document.createElement('span');
      o.className = 'chip';
      o.innerHTML = '<span class="dot" style="background:' + OTHER + '"></span>khác';
      legend.appendChild(o);
    }
    [
      '<span class="dia"></span>ghi chú (⬥ neo vào file)',
      '<span class="dia warn"></span>⚠ ghi chú cần review'
    ].forEach(function (htmlChip) {
      var s2 = document.createElement('span');
      s2.className = 'chip';
      s2.innerHTML = htmlChip;
      legend.appendChild(s2);
    });
    if (LIVE) {
      var live1 = document.createElement('span');
      live1.className = 'chip';
      live1.innerHTML = '<span class="dot" style="background:#57c7ff"></span>agent vừa sửa';
      legend.appendChild(live1);
    }
  }

  // ---- the ship's log: memories on a timeline ----
  function renderLog() {
    var ul = document.getElementById('log');
    ul.innerHTML = '';
    var list = mems.filter(function (m) { return !m.dying; })
      .slice().sort(function (a, b) { return (b.created || 0) - (a.created || 0); });
    list.forEach(function (m) {
      var li = document.createElement('li');
      var d = m.created ? new Date(m.created) : null;
      var ds = d ? pad2(d.getDate()) + '/' + pad2(d.getMonth() + 1) : '—';
      li.innerHTML = '<span class="d">' + ds + '</span>' + (TYPE_ICON[m.type] || '•') + ' ' +
        escH(m.title) + (m.status === 'needs_review' ? ' <span class="warn">⚠</span>' : '');
      li.addEventListener('click', function () { focusEntityById(m.id); });
      ul.appendChild(li);
    });
  }
  function pad2(n) { return (n < 10 ? '0' : '') + n; }

  // ---- the activity band: what is happening right now (live only) ----
  var lastFeedKey = '', lastFeedAt = 0;
  function feedEvent(ev) {
    var icon = ev[0], cls = ev[1], label = ev[2], targetId = ev[3];
    var key = icon + label;
    var t = Date.now();
    if (key === lastFeedKey && t - lastFeedAt < 4000) return;
    lastFeedKey = key; lastFeedAt = t;
    var ul = document.getElementById('feed');
    var li = document.createElement('li');
    var d = new Date();
    li.innerHTML = '<span class="t">' + pad2(d.getHours()) + ':' + pad2(d.getMinutes()) + ':' +
      pad2(d.getSeconds()) + '</span><span class="' + cls + '">' + icon + '</span> ' + escH(label);
    if (targetId) li.addEventListener('click', function () { focusEntityById(targetId); });
    ul.insertBefore(li, ul.firstChild);
    while (ul.children.length > 120) ul.removeChild(ul.lastChild);
  }
  function focusEntityById(id) {
    var e = byId[id] || memById[id];
    if (!e) return;
    select(e);
    cam.x = e.x; cam.y = e.y;
  }

  // ---- animation: recent activity glows, newborns bloom, the deleted fade ----
  function heatOf(o) {
    var t = (frameNow - o.hotAt) / HEAT_MS;
    if (t < 0 || t >= 1) return 0;
    var u = 1 - t;
    return u * u;
  }
  function enterK(o) {
    var t = (frameNow - o.born) / ENTER_MS;
    if (t >= 1) return 1;
    if (t < 0) return 0;
    return 1 - Math.pow(1 - t, 3);
  }
  function fadeK(o) {
    if (!o.dying) return 1;
    return Math.max(0, 1 - (frameNow - o.dying) / EXIT_MS);
  }

  // ---- canvases ----
  var canvas = document.getElementById('canvas');
  var ctx = canvas.getContext('2d');
  var globeCanvas = document.getElementById('globe');
  var gtx = globeCanvas.getContext('2d');
  var W = 1200, H = 800, GW = 300, GH = 200;
  var cam = { x: 0, y: 0, k: 1 };
  var gOrb = { yaw: 0.6, pitch: 0.3, dist: 900 };
  var gZoom = 1, gInteracting = false;
  var PERSP = 620;
  var dpr = Math.max(1, window.devicePixelRatio || 1);
  function sizeCanvas(cv, stage) {
    var w = stage.clientWidth, h = stage.clientHeight;
    cv.width = Math.max(1, w * dpr); cv.height = Math.max(1, h * dpr);
    cv.style.width = w + 'px'; cv.style.height = h + 'px';
    return [w, h];
  }
  function resize() {
    var a = sizeCanvas(canvas, document.getElementById('chartStage'));
    W = a[0]; H = a[1];
    var b = sizeCanvas(globeCanvas, document.getElementById('globeStage'));
    GW = b[0]; GH = b[1];
  }
  window.addEventListener('resize', resize);
  resize();

  function project(n) {
    n.sx = W / 2 + (n.x - cam.x) * cam.k;
    n.sy = H / 2 + (n.y - cam.y) * cam.k;
    n.sr = n.r * cam.k * enterK(n);
    n.sOn = true;
  }
  // the chart frames itself until the reader takes the wheel (drag/zoom)
  var autoFit = true;
  function fitChart() {
    var i, n, found = false;
    var minX = 0, maxX = 0, minY = 0, maxY = 0;
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      if (n.dying || !visible(n)) continue;
      if (!found) { minX = maxX = n.x; minY = maxY = n.y; found = true; }
      else {
        if (n.x < minX) minX = n.x;
        if (n.x > maxX) maxX = n.x;
        if (n.y < minY) minY = n.y;
        if (n.y > maxY) maxY = n.y;
      }
    }
    if (!found) return;
    var bw = Math.max(120, maxX - minX + 150), bh = Math.max(120, maxY - minY + 150);
    var tk = Math.min(1.6, Math.max(0.25, Math.min(W / bw, H / bh)));
    cam.k += (tk - cam.k) * 0.08;
    cam.x += ((minX + maxX) / 2 - cam.x) * 0.08;
    cam.y += ((minY + maxY) / 2 - cam.y) * 0.08;
  }
  // globe framing: centroid + spread of the cloud, recomputed each frame
  var gCx = 0, gCy = 0, gCz = 0, gDist = 900, gR = 400;
  function frameGlobe() {
    var i, n, c = 0, sx = 0, sy2 = 0, sz = 0;
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      if (n.dying) continue;
      sx += n.x; sy2 += n.y; sz += n.z; c++;
    }
    if (c === 0) return;
    gCx = sx / c; gCy = sy2 / c; gCz = sz / c;
    var r2 = 0;
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      if (n.dying) continue;
      var dx = n.x - gCx, dy = n.y - gCy, dz = n.z - gCz;
      var d2 = dx * dx + dy * dy + dz * dz;
      if (d2 > r2) r2 = d2;
    }
    // pull far enough back that perspective stops shoving the near side off-center
    var radius = Math.sqrt(r2);
    gR += (radius - gR) * 0.05;
    var target = Math.min(2600, Math.max(700, radius * 3.4));
    gDist += (target - gDist) * 0.05;
  }
  function projectGlobe(n) {
    // the cloud is z-flattened for the 2D chart, so spin it IN its own plane
    // (a chart disc on a tilted table — never edge-on), not around the y axis
    var cy = Math.cos(gOrb.yaw), sy = Math.sin(gOrb.yaw);
    var cp = Math.cos(gOrb.pitch), sp = Math.sin(gOrb.pitch);
    var ox = n.x - gCx, oy = n.y - gCy, oz = n.z - gCz;
    var x1 = ox * cy - oy * sy;
    var y1 = ox * sy + oy * cy;
    var y2 = y1 * cp - oz * sp;
    var z2 = y1 * sp + oz * cp;
    var d = z2 + gDist * gZoom;
    if (d < 80) { n.gOn = false; return; }
    // exact-fit scale (cloud ≈ 82% of the frame's short side), perspective only modulates
    var s = ((Math.min(GW, GH) * 0.41) / Math.max(1, gR)) * (gDist / d);
    n.gx = GW / 2 + x1 * s;
    n.gy = GH / 2 + y2 * s;
    n.gr = Math.max(1, n.r * s * 0.85) * enterK(n);
    n.gdepth = Math.max(0.15, Math.min(1, 950 / d));
    n.gOn = true;
  }
  function toWorld2D(px, py) { return [(px - W / 2) / cam.k + cam.x, (py - H / 2) / cam.k + cam.y]; }

  // ---- filters ----
  var showImports = true, showCochange = true, onlyMem = false, allEdges = false, showMems = true, query = '';
  function visible(n) { return !(onlyMem && n.mems.length === 0); }
  function memVisible(m) {
    if (!showMems) return false;
    return m.files.some(function (fn) { return visible(fn); }) || m.files.length === 0;
  }
  function matches(n) { return query === '' || n.id.toLowerCase().indexOf(query) !== -1; }
  function memMatches(m) {
    if (query === '') return true;
    if ((m.title + ' ' + m.body).toLowerCase().indexOf(query) !== -1) return true;
    return m.files.some(matches);
  }

  // ---- simulation (one 3D force field; the 2D chart flattens z with a spring) ----
  var alpha = 1;
  function tick() {
    var i, j, n, m, e;
    var centroids = {};
    for (i = 0; i < dirs.length; i++) centroids[dirs[i]] = { x: 0, y: 0, z: 0, c: 0 };
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i]; var c = centroids[n.dir];
      c.x += n.x; c.y += n.y; c.z += n.z; c.c++;
    }
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      for (j = i + 1; j < nodes.length; j++) {
        m = nodes[j];
        var dx = n.x - m.x, dy = n.y - m.y, dz = n.z - m.z;
        var d2 = dx * dx + dy * dy + dz * dz + 0.01;
        if (d2 > 130000) continue;
        var f = (n.dir === m.dir ? 1500 : 2600) / d2;
        var dl = Math.sqrt(d2);
        dx /= dl; dy /= dl; dz /= dl;
        n.vx += dx * f; n.vy += dy * f; n.vz += dz * f;
        m.vx -= dx * f; m.vy -= dy * f; m.vz -= dz * f;
      }
      var ct = centroids[n.dir];
      if (ct.c > 0) {
        n.vx += (ct.x / ct.c - n.x) * 0.035;
        n.vy += (ct.y / ct.c - n.y) * 0.035;
        n.vz += (ct.z / ct.c - n.z) * 0.035;
      }
      n.vx += -n.x * 0.0025; n.vy += -n.y * 0.0025; n.vz += -n.z * 0.0025;
      n.vz += -n.z * 0.09; // z-spring: the chart reads flat; the globe shows the disk
    }
    for (i = 0; i < edges.length; i++) {
      e = edges[i];
      var rest = e.kind === 'imports' ? 100 : 75;
      var k = e.kind === 'imports' ? 0.018 : 0.028;
      var ex = e.b.x - e.a.x, ey = e.b.y - e.a.y, ez = e.b.z - e.a.z;
      var el = Math.sqrt(ex * ex + ey * ey + ez * ez) + 0.01;
      var s = k * (el - rest) / el;
      e.a.vx += ex * s; e.a.vy += ey * s; e.a.vz += ez * s;
      e.b.vx -= ex * s; e.b.vy -= ey * s; e.b.vz -= ez * s;
    }
    // memory satellites: tether springs to anchors + gentle mem-mem repulsion
    for (i = 0; i < mems.length; i++) {
      m = mems[i];
      for (j = 0; j < m.files.length; j++) {
        n = m.files[j];
        var mx = n.x - m.x, my = n.y - m.y, mz = n.z - m.z;
        var ml = Math.sqrt(mx * mx + my * my + mz * mz) + 0.01;
        var ms = 0.09 * (ml - 42) / ml;
        m.vx += mx * ms; m.vy += my * ms; m.vz += mz * ms;
      }
      for (j = i + 1; j < mems.length; j++) {
        var m2 = mems[j];
        var rx = m.x - m2.x, ry = m.y - m2.y, rz = m.z - m2.z;
        var rd2 = rx * rx + ry * ry + rz * rz + 0.01;
        if (rd2 > 16000) continue;
        var rf = 500 / rd2;
        var rl = Math.sqrt(rd2);
        rx /= rl; ry /= rl; rz /= rl;
        m.vx += rx * rf; m.vy += ry * rf; m.vz += rz * rf;
        m2.vx -= rx * rf; m2.vy -= ry * rf; m2.vz -= rz * rf;
      }
      // keep the diamond out of its own anchor's disc
      for (j = 0; j < m.files.length; j++) {
        n = m.files[j];
        var px2 = m.x - n.x, py2 = m.y - n.y, pz2 = m.z - n.z;
        var pd = Math.sqrt(px2 * px2 + py2 * py2 + pz2 * pz2) + 0.01;
        var minD = n.r + 14;
        if (pd < minD) {
          var pf = (minD - pd) * 0.12;
          m.vx += (px2 / pd) * pf; m.vy += (py2 / pd) * pf; m.vz += (pz2 / pd) * pf;
        }
      }
      m.vz += -m.z * 0.09;
      m.vx *= 0.8; m.vy *= 0.8; m.vz *= 0.8;
      m.x += m.vx * alpha; m.y += m.vy * alpha; m.z += m.vz * alpha;
    }
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      if (n.pinned) { n.vx = 0; n.vy = 0; n.vz = 0; continue; }
      n.vx *= 0.82; n.vy *= 0.82; n.vz *= 0.82;
      n.x += n.vx * alpha; n.y += n.vy * alpha; n.z += n.vz * alpha;
    }
    if (alpha > 0.02) alpha *= 0.995;
  }

  // ---- territory hulls ----
  function hullOf(points) {
    if (points.length < 3) return points.slice();
    points = points.slice().sort(function (p, q) { return p[0] - q[0] || p[1] - q[1]; });
    var cross = function (o, a, b) {
      return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);
    };
    var lower = [], upper = [], i;
    for (i = 0; i < points.length; i++) {
      while (lower.length >= 2 && cross(lower[lower.length - 2], lower[lower.length - 1], points[i]) <= 0) lower.pop();
      lower.push(points[i]);
    }
    for (i = points.length - 1; i >= 0; i--) {
      while (upper.length >= 2 && cross(upper[upper.length - 2], upper[upper.length - 1], points[i]) <= 0) upper.pop();
      upper.push(points[i]);
    }
    lower.pop(); upper.pop();
    return lower.concat(upper);
  }
  function hexA(hex, a) {
    var r = parseInt(hex.slice(1, 3), 16), g = parseInt(hex.slice(3, 5), 16), b = parseInt(hex.slice(5, 7), 16);
    return 'rgba(' + r + ',' + g + ',' + b + ',' + a + ')';
  }
  function drawTerritories() {
    dirs.forEach(function (d) {
      var pts = [], topPt = null;
      nodes.forEach(function (n) {
        if (n.dir !== d || !visible(n) || !n.sOn) return;
        var p = [n.sx, n.sy];
        pts.push(p);
        if (!topPt || p[1] < topPt[1]) topPt = p;
      });
      if (pts.length === 0) return;
      var hull = hullOf(pts);
      var pad = 26 * Math.min(1.4, Math.max(0.6, cam.k));
      ctx.beginPath();
      if (hull.length === 1) {
        ctx.arc(hull[0][0], hull[0][1], pad, 0, 7);
      } else {
        ctx.moveTo(hull[0][0], hull[0][1]);
        for (var i = 1; i < hull.length; i++) ctx.lineTo(hull[i][0], hull[i][1]);
        ctx.closePath();
      }
      ctx.fillStyle = hexA(dirColor[d], 0.05);
      ctx.strokeStyle = hexA(dirColor[d], 0.16);
      ctx.lineWidth = pad * 2;
      ctx.lineJoin = 'round'; ctx.lineCap = 'round';
      ctx.stroke(); ctx.fill();
      if (topPt && cam.k > 0.45) {
        ctx.font = '600 11px system-ui, sans-serif';
        ctx.fillStyle = hexA(dirColor[d], 0.75);
        ctx.fillText(d, topPt[0] - 8, topPt[1] - pad - 8);
      }
    });
  }

  // ---- drawing ----
  var hover = null, selected = null;
  function focusEntity() { return hover || selected; }
  function drawArrow(x1, y1, x2, y2, rTarget, color) {
    var dx = x2 - x1, dy = y2 - y1;
    var len = Math.sqrt(dx * dx + dy * dy);
    if (len < 1) return;
    dx /= len; dy /= len;
    var tipX = x2 - dx * (rTarget + 4), tipY = y2 - dy * (rTarget + 4);
    var s = 6;
    ctx.beginPath();
    ctx.moveTo(tipX, tipY);
    ctx.lineTo(tipX - dx * s - dy * s * 0.6, tipY - dy * s + dx * s * 0.6);
    ctx.lineTo(tipX - dx * s + dy * s * 0.6, tipY - dy * s - dx * s * 0.6);
    ctx.closePath();
    ctx.fillStyle = color;
    ctx.fill();
  }
  function drawDiamond(c2, x, y, r, fill, dim) {
    c2.beginPath();
    c2.moveTo(x, y - r);
    c2.lineTo(x + r, y);
    c2.lineTo(x, y + r);
    c2.lineTo(x - r, y);
    c2.closePath();
    c2.fillStyle = fill;
    c2.fill();
    c2.strokeStyle = dim ? 'rgba(13,13,13,0.4)' : '#0d0d0d';
    c2.lineWidth = 1;
    c2.stroke();
  }

  function draw() {
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, W, H);
    var i, e, n, m;
    for (i = 0; i < nodes.length; i++) project(nodes[i]);
    for (i = 0; i < mems.length; i++) project(mems[i]);
    drawTerritories();

    var f = focusEntity();
    var fIsMem = f && f.kind === 'mem';
    var fIsFile = f && f.kind === 'file';

    // file↔file edges (spotlight: only the focused file's edges; none when a memory is focused)
    for (i = 0; i < edges.length; i++) {
      e = edges[i];
      if (e.kind === 'imports' && !showImports) continue;
      if (e.kind === 'co_change' && !showCochange) continue;
      if (!visible(e.a) || !visible(e.b) || !e.a.sOn || !e.b.sOn) continue;
      var incident = fIsFile && (e.a === f || e.b === f);
      if (f && !incident) continue;
      var queryDim = query !== '' && !(matches(e.a) && matches(e.b));
      ctx.beginPath();
      ctx.moveTo(e.a.sx, e.a.sy); ctx.lineTo(e.b.sx, e.b.sy);
      if (incident) {
        if (e.kind === 'co_change') {
          ctx.setLineDash([5, 4]);
          ctx.strokeStyle = 'rgba(232,230,218,0.95)';
          ctx.lineWidth = 1.6 + Math.min(2, e.w * 2);
        } else {
          ctx.setLineDash([]);
          ctx.strokeStyle = 'rgba(195,194,183,0.95)';
          ctx.lineWidth = 1.6;
        }
        ctx.stroke();
        if (e.kind === 'imports') {
          drawArrow(e.a.sx, e.a.sy, e.b.sx, e.b.sy, e.b.sr, '#c3c2b7');
        }
      } else {
        var base = allEdges ? 0.5 : 0.14;
        if (e.kind === 'co_change') {
          ctx.setLineDash([5, 4]);
          ctx.strokeStyle = 'rgba(195,194,183,' + (queryDim ? 0.04 : base) + ')';
          ctx.lineWidth = 1 + Math.min(2, e.w * 1.5);
        } else {
          ctx.setLineDash([]);
          ctx.strokeStyle = 'rgba(137,135,129,' + (queryDim ? 0.03 : base) + ')';
          ctx.lineWidth = 1;
        }
        ctx.stroke();
      }
    }
    ctx.setLineDash([]);

    // memory tethers
    if (showMems) {
      for (i = 0; i < mems.length; i++) {
        m = mems[i];
        if (!memVisible(m) || !m.sOn) continue;
        var mLit = f && (m === f || (fIsFile && m.files.indexOf(f) !== -1));
        if (f && !mLit) continue;
        var warm = m.status === 'needs_review';
        for (var j2 = 0; j2 < m.files.length; j2++) {
          n = m.files[j2];
          if (!visible(n) || !n.sOn) continue;
          var aT = mLit ? 0.9 : 0.3;
          ctx.beginPath();
          ctx.moveTo(m.sx, m.sy); ctx.lineTo(n.sx, n.sy);
          ctx.setLineDash([2, 3]);
          ctx.strokeStyle = warm
            ? 'rgba(250,178,25,' + aT + ')'
            : 'rgba(255,255,255,' + aT * 0.8 + ')';
          ctx.lineWidth = mLit ? 1.4 : 1;
          ctx.stroke();
        }
      }
      ctx.setLineDash([]);
    }

    // file nodes
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      if (!visible(n) || !n.sOn) continue;
      var isFocus = fIsFile && n === f;
      var isNbr = (fIsFile && f.nbr[n.idx]) || (fIsMem && f.files.indexOf(n) !== -1);
      var recede = f ? !(isFocus || isNbr) : false;
      var queryDim2 = query !== '' && !matches(n);
      var hv = heatOf(n);
      ctx.globalAlpha = (queryDim2 ? 0.08 : recede ? 0.14 : 1) * fadeK(n);
      if (n.stale) {
        ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr + 5, 0, 7); ctx.strokeStyle = '#fab219';
        ctx.lineWidth = 2.5; ctx.stroke();
      }
      if (n.mems.length > 0) {
        ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr + 2, 0, 7); ctx.strokeStyle = '#ffffff';
        ctx.lineWidth = 1.6; ctx.stroke();
      }
      ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr, 0, 7);
      ctx.fillStyle = n.color; ctx.fill();
      if (hv > 0.01) {
        // being worked on right now: hot core + halo + one launch ripple
        // (white = a human/tool saved it; cyan = the agent's own edit — hook-attributed)
        var hc = n.hotSrc === 'agent' ? '87,199,255' : '255,255,255';
        ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr, 0, 7);
        ctx.fillStyle = 'rgba(' + hc + ',' + (0.45 * hv) + ')'; ctx.fill();
        ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr + 3 + 6 * hv, 0, 7);
        ctx.strokeStyle = 'rgba(' + hc + ',' + (0.55 * hv) + ')';
        ctx.lineWidth = 1.5 + 2 * hv; ctx.stroke();
        var rt = (frameNow - n.hotAt) / RIPPLE_MS;
        if (!NO_MOTION && rt >= 0 && rt < 1) {
          ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr + 6 + rt * 46, 0, 7);
          ctx.strokeStyle = 'rgba(' + hc + ',' + (0.4 * (1 - rt)) + ')';
          ctx.lineWidth = 1.5; ctx.stroke();
        }
      }
      if (isFocus || n === selected) {
        ctx.beginPath(); ctx.arc(n.sx, n.sy, n.sr + 8, 0, 7);
        ctx.strokeStyle = 'rgba(255,255,255,0.4)'; ctx.lineWidth = 1.2; ctx.stroke();
      }
      var showLabel =
        isFocus || isNbr || n === selected || hv > 0.2 ||
        (!f && (cam.k > 1.35 || n === hover || (n.mems.length > 0 && cam.k > 0.9)));
      if (showLabel && !queryDim2 && !recede) {
        var name = n.id.split('/').pop();
        ctx.font = (isFocus ? '600 ' : '') + '11px system-ui, sans-serif';
        ctx.fillStyle = isFocus || isNbr ? '#ffffff' : '#898781';
        ctx.fillText(name, n.sx + n.sr + 6, n.sy + 4);
      }
      ctx.globalAlpha = 1;
    }

    // memory diamonds on top — knowledge floats above the code
    if (showMems) {
      for (i = 0; i < mems.length; i++) {
        m = mems[i];
        if (!memVisible(m) || !m.sOn) continue;
        var mFocus = fIsMem && m === f;
        var mNbr = fIsFile && m.files.indexOf(f) !== -1;
        var mRecede = f ? !(mFocus || mNbr) : false;
        var mQueryDim = query !== '' && !memMatches(m);
        var mhv = heatOf(m);
        ctx.globalAlpha = (mQueryDim ? 0.08 : mRecede ? 0.14 : 1) * fadeK(m);
        var mr = Math.max(3.5, m.r * cam.k) * enterK(m);
        if (mFocus || m === selected) {
          ctx.beginPath(); ctx.arc(m.sx, m.sy, mr + 7, 0, 7);
          ctx.strokeStyle = 'rgba(255,255,255,0.4)'; ctx.lineWidth = 1.2; ctx.stroke();
        }
        drawDiamond(ctx, m.sx, m.sy, mr, m.status === 'needs_review' ? '#fab219' : '#e8e6da', mRecede);
        if (mhv > 0.01) {
          ctx.beginPath();
          ctx.moveTo(m.sx, m.sy - mr); ctx.lineTo(m.sx + mr, m.sy);
          ctx.lineTo(m.sx, m.sy + mr); ctx.lineTo(m.sx - mr, m.sy);
          ctx.closePath();
          ctx.fillStyle = 'rgba(255,255,255,' + (0.5 * mhv) + ')'; ctx.fill();
          ctx.beginPath(); ctx.arc(m.sx, m.sy, mr + 3 + 6 * mhv, 0, 7);
          ctx.strokeStyle = 'rgba(255,255,255,' + (0.55 * mhv) + ')';
          ctx.lineWidth = 1.5 + 2 * mhv; ctx.stroke();
          var mrt = (frameNow - m.hotAt) / RIPPLE_MS;
          if (!NO_MOTION && mrt >= 0 && mrt < 1) {
            ctx.beginPath(); ctx.arc(m.sx, m.sy, mr + 6 + mrt * 40, 0, 7);
            ctx.strokeStyle = 'rgba(255,255,255,' + (0.4 * (1 - mrt)) + ')';
            ctx.lineWidth = 1.5; ctx.stroke();
          }
        }
        var showT = mFocus || mNbr || m === selected || mhv > 0.2 ||
          (!f && (m === hover || cam.k > 1.2));
        if (showT && !mQueryDim && !mRecede) {
          ctx.font = '11px system-ui, sans-serif';
          ctx.fillStyle = mFocus ? '#ffffff' : '#c3c2b7';
          ctx.fillText((TYPE_ICON[m.type] || '•') + ' ' + m.title, m.sx + mr + 6, m.sy + 4);
        }
        ctx.globalAlpha = 1;
      }
    }
  }

  // ---- the 3D globe: a second projection of the same simulation, always turning ----
  function drawGlobe() {
    gtx.setTransform(dpr, 0, 0, dpr, 0, 0);
    gtx.clearRect(0, 0, GW, GH);
    if (!NO_MOTION && !gInteracting) gOrb.yaw += 0.0035;
    var i, n, m;
    for (i = 0; i < nodes.length; i++) projectGlobe(nodes[i]);
    for (i = 0; i < mems.length; i++) projectGlobe(mems[i]);
    var order = nodes.slice().sort(function (p, q) { return p.gdepth - q.gdepth; });
    for (i = 0; i < edges.length; i++) {
      var e = edges[i];
      if (!e.a.gOn || !e.b.gOn || !visible(e.a) || !visible(e.b)) continue;
      var dMul = Math.min(e.a.gdepth, e.b.gdepth);
      gtx.beginPath();
      gtx.moveTo(e.a.gx, e.a.gy); gtx.lineTo(e.b.gx, e.b.gy);
      gtx.strokeStyle = 'rgba(137,135,129,' + (0.10 * dMul) + ')';
      gtx.lineWidth = 0.7;
      gtx.stroke();
    }
    for (i = 0; i < order.length; i++) {
      n = order[i];
      if (!n.gOn || !visible(n)) continue;
      var hv = heatOf(n);
      gtx.globalAlpha = (0.35 + 0.65 * n.gdepth) * fadeK(n);
      if (n.mems.length > 0) {
        gtx.beginPath(); gtx.arc(n.gx, n.gy, n.gr + 1.5, 0, 7);
        gtx.strokeStyle = n.stale ? '#fab219' : 'rgba(255,255,255,0.8)';
        gtx.lineWidth = 1.1; gtx.stroke();
      }
      gtx.beginPath(); gtx.arc(n.gx, n.gy, n.gr, 0, 7);
      gtx.fillStyle = n.color; gtx.fill();
      if (hv > 0.02) {
        var hc = n.hotSrc === 'agent' ? '87,199,255' : '255,255,255';
        gtx.beginPath(); gtx.arc(n.gx, n.gy, n.gr + 2 + 3 * hv, 0, 7);
        gtx.strokeStyle = 'rgba(' + hc + ',' + (0.5 * hv) + ')';
        gtx.lineWidth = 1.2; gtx.stroke();
      }
      if (n === selected) {
        gtx.beginPath(); gtx.arc(n.gx, n.gy, n.gr + 6, 0, 7);
        gtx.strokeStyle = 'rgba(255,255,255,0.55)'; gtx.lineWidth = 1.3; gtx.stroke();
      }
      if (n === selected || hv > 0.25) {
        gtx.font = '10px system-ui, sans-serif';
        gtx.fillStyle = n === selected ? '#ffffff' : '#c3c2b7';
        gtx.fillText(n.id.split('/').pop(), n.gx + n.gr + 5, n.gy + 3);
      }
      gtx.globalAlpha = 1;
    }
    if (showMems) {
      var morder = mems.slice().sort(function (p, q) { return p.gdepth - q.gdepth; });
      for (i = 0; i < morder.length; i++) {
        m = morder[i];
        if (!m.gOn || !memVisible(m)) continue;
        var mhv = heatOf(m);
        gtx.globalAlpha = (0.4 + 0.6 * m.gdepth) * fadeK(m);
        drawDiamond(gtx, m.gx, m.gy, Math.max(2, m.gr * 0.8),
          m.status === 'needs_review' ? '#fab219' : '#e8e6da', false);
        if (m === selected) {
          gtx.beginPath(); gtx.arc(m.gx, m.gy, Math.max(2, m.gr * 0.8) + 5, 0, 7);
          gtx.strokeStyle = 'rgba(255,255,255,0.55)'; gtx.lineWidth = 1.3; gtx.stroke();
        }
        if (m === selected || mhv > 0.25) {
          gtx.font = '10px system-ui, sans-serif';
          gtx.fillStyle = m === selected ? '#ffffff' : '#c3c2b7';
          gtx.fillText((TYPE_ICON[m.type] || '•') + ' ' + m.title, m.gx + m.gr + 5, m.gy + 3);
        }
        gtx.globalAlpha = 1;
      }
    }
  }

  function loop() {
    frameNow = performance.now();
    pruneDead(frameNow);
    tick();
    if (autoFit) fitChart();
    frameGlobe();
    draw();
    drawGlobe();
    requestAnimationFrame(loop);
  }
  requestAnimationFrame(loop);

  // ---- interaction (2D chart only; the globe is an instrument, not a control) ----
  var tipEl = document.getElementById('tip');
  function pick(px, py) {
    var best = null, i, d;
    if (showMems) {
      for (i = 0; i < mems.length; i++) {
        var m = mems[i];
        if (m.dying || !memVisible(m) || !m.sOn) continue;
        d = Math.hypot(m.sx - px, m.sy - py);
        if (d < Math.max(11, m.sr + 7)) { best = m; }
      }
      if (best) return best; // diamonds sit on top — they win ties
    }
    for (i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.dying || !visible(n) || !n.sOn) continue;
      d = Math.hypot(n.sx - px, n.sy - py);
      if (d < Math.max(12, n.sr + 6)) { best = n; }
    }
    return best;
  }
  var dragNode = null, panning = false, lastX = 0, lastY = 0, moved = false;
  var downEntity = null;
  canvas.addEventListener('mousedown', function (ev) {
    autoFit = false; // the reader takes the wheel
    var r = canvas.getBoundingClientRect();
    var px = ev.clientX - r.left, py = ev.clientY - r.top;
    downEntity = pick(px, py);
    if (downEntity && downEntity.kind === 'file') {
      dragNode = downEntity;
      dragNode.pinned = true;
      alpha = Math.max(alpha, 0.3);
    } else {
      panning = true;
    }
    lastX = px; lastY = py; moved = false;
    canvas.classList.add('dragging');
  });
  window.addEventListener('mousemove', function (ev) {
    var r = canvas.getBoundingClientRect();
    var px = ev.clientX - r.left, py = ev.clientY - r.top;
    if (dragNode) {
      var w = toWorld2D(px, py);
      dragNode.x = w[0]; dragNode.y = w[1]; moved = true;
    } else if (panning) {
      cam.x -= (px - lastX) / cam.k; cam.y -= (py - lastY) / cam.k;
      lastX = px; lastY = py; moved = true;
    } else {
      var h = pick(px, py);
      hover = h;
      if (h && h.kind === 'mem') {
        tipEl.style.display = 'block';
        tipEl.style.left = (px + 14) + 'px'; tipEl.style.top = (py + 14) + 'px';
        var flag = h.status === 'needs_review' ? ' <span style="color:#fab219">⚠ cần review</span>' : '';
        tipEl.innerHTML = '<b>' + (TYPE_ICON[h.type] || '•') + ' ' + escH(h.title) + '</b>' + flag +
          '<br>' + escH(h.body) + '<br><span style="color:#898781">neo: ' +
          h.files.map(function (fn) { return escH(fn.id); }).join(' · ') + '</span>';
      } else if (h) {
        tipEl.style.display = 'block';
        tipEl.style.left = (px + 14) + 'px'; tipEl.style.top = (py + 14) + 'px';
        var extra = h.mems.length ? ' · ' + h.mems.length + ' ghi chú' : '';
        var warn2 = h.stale ? ' · <span style="color:#fab219">⚠ cần review</span>' : '';
        tipEl.innerHTML = '<b>' + escH(h.id) + '</b><br>' + h.symbols + ' symbol · ' + h.deg +
          ' liên kết' + extra + warn2;
      } else tipEl.style.display = 'none';
    }
  });
  window.addEventListener('mouseup', function () {
    canvas.classList.remove('dragging');
    if (dragNode && !moved) select(dragNode);
    if (!dragNode && !moved && downEntity && downEntity.kind === 'mem') select(downEntity);
    if (!dragNode && panning && !moved && !downEntity) select(null);
    if (dragNode) dragNode.pinned = false;
    dragNode = null; panning = false; downEntity = null;
  });
  canvas.addEventListener('wheel', function (ev) {
    ev.preventDefault();
    autoFit = false;
    var r = canvas.getBoundingClientRect();
    var px = ev.clientX - r.left, py = ev.clientY - r.top;
    var w = toWorld2D(px, py);
    var k2 = Math.min(6, Math.max(0.25, cam.k * (ev.deltaY < 0 ? 1.15 : 0.87)));
    cam.x = w[0] - (px - W / 2) / k2;
    cam.y = w[1] - (py - H / 2) / k2;
    cam.k = k2;
  }, { passive: false });

  // globe: drag = orbit, wheel = dolly, click = inspect (rotation pauses while held)
  var gDragging = false, gLastX = 0, gLastY = 0, gMoved = false;
  function gPick(px, py) {
    var best = null, bestD = -1, i;
    if (showMems) {
      for (i = 0; i < mems.length; i++) {
        var m = mems[i];
        if (m.dying || !memVisible(m) || !m.gOn) continue;
        if (Math.hypot(m.gx - px, m.gy - py) < Math.max(9, m.gr + 6) && m.gdepth > bestD) {
          best = m; bestD = m.gdepth;
        }
      }
      if (best) return best;
    }
    for (i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.dying || !visible(n) || !n.gOn) continue;
      if (Math.hypot(n.gx - px, n.gy - py) < Math.max(10, n.gr + 5) && n.gdepth > bestD) {
        best = n; bestD = n.gdepth;
      }
    }
    return best;
  }
  globeCanvas.addEventListener('mousedown', function (ev) {
    gDragging = true; gInteracting = true; gMoved = false;
    var r = globeCanvas.getBoundingClientRect();
    gLastX = ev.clientX - r.left; gLastY = ev.clientY - r.top;
    globeCanvas.classList.add('dragging');
  });
  window.addEventListener('mousemove', function (ev) {
    if (!gDragging) return;
    var r = globeCanvas.getBoundingClientRect();
    var px = ev.clientX - r.left, py = ev.clientY - r.top;
    var dx = px - gLastX, dy = py - gLastY;
    gOrb.yaw += dx * 0.005;
    gOrb.pitch = Math.max(-1.35, Math.min(1.35, gOrb.pitch + dy * 0.005));
    gLastX = px; gLastY = py;
    if (Math.abs(dx) + Math.abs(dy) > 2) gMoved = true;
  });
  window.addEventListener('mouseup', function (ev) {
    if (!gDragging) return;
    gDragging = false; gInteracting = false;
    globeCanvas.classList.remove('dragging');
    if (!gMoved) {
      var r = globeCanvas.getBoundingClientRect();
      var picked = gPick(ev.clientX - r.left, ev.clientY - r.top);
      select(picked || null);
    }
  });
  globeCanvas.addEventListener('wheel', function (ev) {
    ev.preventDefault();
    gZoom = Math.min(2.6, Math.max(0.45, gZoom * (ev.deltaY < 0 ? 0.9 : 1.12)));
  }, { passive: false });

  // ---- inspector: structure + meaning of the selection ----
  var inspector = document.getElementById('inspector');
  function escH(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function memCard(m, clickable) {
    var flag = m.status === 'needs_review' ? ' <span class="flag">⚠ cần review (code đã đổi)</span>' : '';
    var created = m.created
      ? '<span style="float:right;color:var(--ink-3)">tạo: ' +
        new Date(m.created).toISOString().slice(0, 10) + '</span>'
      : '';
    return '<div class="mem" data-mem="' + escH(m.id) + '"' + (clickable ? '' : ' style="cursor:default"') + '>' +
      '<div class="t">' + (TYPE_ICON[m.type] || '•') + ' ' + escH(m.title) + flag + '</div>' +
      '<div class="body2">' + escH(m.body) + '</div>' +
      '<div class="why">vì: ' + escH(m.why) + ' · ' + escH(m.id) + created + '</div></div>';
  }
  function select(n) {
    selected = n;
    if (!n) {
      inspector.innerHTML = '<div class="empty">Chưa chọn gì — click một node hoặc ⬥ trên hải đồ</div>';
      return;
    }
    var html = '<button class="close" title="đóng">✕</button>';
    if (n.kind === 'mem') {
      html += '<h2>' + (TYPE_ICON[n.type] || '•') + ' Ghi chú — ' + escH(n.type.toUpperCase()) + '</h2>';
      html += '<div class="meta">' + escH(n.id) + '</div>';
      html += memCard(n, false);
      html += '<div class="sec">Neo vào</div>';
      n.files.forEach(function (fn) {
        html += '<div class="edge" data-path="' + escH(fn.id) + '">' + escH(fn.id) + '</div>';
      });
      n.anchors.forEach(function (a) {
        if (a.qname && a.qname !== a.path) {
          html += '<div class="meta">↳ ' + escH(a.qname) + '</div>';
        }
      });
    } else {
      html += '<h2>' + escH(n.id) + '</h2>';
      html += '<div class="meta"><span style="display:inline-block;width:9px;height:9px;border-radius:50%;background:' + n.color + '"></span> ' +
        escH(n.dir) + ' · ' + n.symbols + ' symbol · ' + n.deg + ' liên kết</div>';
      html += '<div class="sec">Cấu trúc</div>';
      if (n.syms && n.syms.length > 0) {
        n.syms.forEach(function (s) {
          html += '<div class="sym" title="' + escH(s.sig || '') + '">' +
            '<span class="k">' + (KIND_ICON[s.k] || '•') + '</span>' + escH(s.n) +
            '<span class="ln">L' + s.l1 + '–' + s.l2 + '</span></div>';
        });
      } else {
        html += '<div class="meta">(file tài liệu — neo ghi chú ở mức file)</div>';
      }
      if (n.mems.length > 0) {
        html += '<div class="sec">Ghi chú neo ở đây (click để soi)</div>';
        n.mems.forEach(function (m) { html += memCard(m, true); });
      } else {
        html += '<div class="sec">Chưa có ghi chú nào ở file này</div>';
      }
      var rel = { 'import →': [], '← được import bởi': [], 'hay đổi cùng nhau': [] };
      edges.forEach(function (e) {
        if (e.kind === 'imports') {
          if (e.a === n) rel['import →'].push(e.b.id);
          else if (e.b === n) rel['← được import bởi'].push(e.a.id);
        } else if (e.a === n || e.b === n) {
          rel['hay đổi cùng nhau'].push(e.a === n ? e.b.id : e.a.id);
        }
      });
      var relKeys = Object.keys(rel);
      var hasRel = relKeys.some(function (k) { return rel[k].length > 0; });
      if (hasRel) html += '<div class="sec">Liên kết</div>';
      relKeys.forEach(function (k) {
        if (rel[k].length === 0) return;
        html += '<div class="meta">' + k + '</div>';
        rel[k].forEach(function (p) {
          html += '<div class="edge" data-path="' + escH(p) + '">' + escH(p) + '</div>';
        });
      });
    }
    inspector.innerHTML = html;
    inspector.querySelector('.close').addEventListener('click', function () { select(null); });
    inspector.querySelectorAll('.edge').forEach(function (el) {
      el.addEventListener('click', function () {
        var target = byId[el.getAttribute('data-path')];
        if (!target) return;
        select(target);
        cam.x = target.x; cam.y = target.y;
      });
    });
    inspector.querySelectorAll('.mem[data-mem]').forEach(function (el) {
      if (el.style.cursor === 'default') return;
      el.addEventListener('click', function () {
        var id = el.getAttribute('data-mem');
        for (var i = 0; i < mems.length; i++) {
          if (mems[i].id === id) { select(mems[i]); break; }
        }
      });
    });
  }

  // ---- controls ----
  var hint = document.getElementById('hint');
  hint.innerHTML = '<b style="color:var(--ink-2)">⬥ = ghi chú trí nhớ neo vào file</b> (vàng ⚠ = cần review) · trỏ/click node hoặc ⬥ để soi liên kết · kéo node/nền · lăn chuột zoom — sinh bởi <kbd>haido viz</kbd>';
  document.getElementById('showMems').addEventListener('change', function (e) { showMems = e.target.checked; });
  document.getElementById('showImports').addEventListener('change', function (e) { showImports = e.target.checked; });
  document.getElementById('showCochange').addEventListener('change', function (e) { showCochange = e.target.checked; });
  document.getElementById('allEdges').addEventListener('change', function (e) { allEdges = e.target.checked; });
  document.getElementById('onlyMem').addEventListener('change', function (e) { onlyMem = e.target.checked; alpha = Math.max(alpha, 0.2); });
  document.getElementById('mapOnly').addEventListener('change', function (e) {
    document.body.classList.toggle('maponly', e.target.checked);
    resize();
  });
  document.getElementById('search').addEventListener('input', function (e) { query = e.target.value.trim().toLowerCase(); });

  // ---- boot ----
  applyData(DATA, null);
  select(null);
  if (!LIVE) document.getElementById('feedEmpty').style.display = 'block';
  else document.getElementById('feedEmpty').style.display = 'none';

  // ---- live mode: the page breathes with the repo (served by \`haido viz --live\`) ----
  if (LIVE) {
    var liveEl = document.getElementById('live');
    liveEl.style.display = 'inline-flex';
    var setLive = function (on) {
      liveEl.className = on ? 'on' : 'off';
      liveEl.textContent = on ? '● trực tiếp' : '○ mất kết nối';
      liveEl.title = on ? 'đang theo dõi thay đổi' : 'tự kết nối lại…';
    };
    setLive(false);
    var es = new EventSource('events');
    es.addEventListener('map', function (ev) {
      var msg = JSON.parse(ev.data);
      applyData(msg.data || {}, msg.hot);
      setLive(true);
    });
    es.onerror = function () { setLive(false); };
  }
})();
</script>
</body>
</html>
`;
